[package]
name = "ourchat-rs"
version = "0.1.0"
authors = ["Ricardo Antunes <me@riscadoa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
igd = "0.12.0"
local-ip-address = "0.4.4"
